### ISSUE TITLE
製作ㄅㄆㄇㄈ注音符號

### ISSUE THREAD

**Issue by zerng07** [l10n-tw/zenjia-fonts#4]
現在靜嘉黑體沒有包含注音符號，因為 cwTeX Q Hei 與 cwTeX Hei Bold 都不是黑體的ㄅㄆㄇㄈ。

**Comment by zerng07** [comment]
終於要畫完了。剩下ㄤ跟ㄦ了！

最慢下週就好了。

**Comment by zerng07** [comment]
粗算一下，歷時九個月啊…

**Comment by Arthur2e5** [comment]
Will those fixes be backported into cwTeX Hei too?

**Comment by zerng07** [comment]
會的！！！

原本我是打算再把貝茲曲線修一下再放過去，但一直沒找到時間…
不然也是可以直接複製過去先推出啦～ XD
